# Spring Configuration
spring:
  application:
    name: mysite07

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

  main:
    allow-bean-definition-overriding: true

  aop:
    auto: true
    proxy-target-class: true

  #Message Source (Locale Setting (i18n)) message.properties 기본이 있어야함
  messages:
    basename: messages/message
    encoding: UTF-8

  #JSP
  mvc:
#    view:
#      suffix: .jsp
#      prefix: /WEB-INF/views/
    static-path-pattern: /assets/**

  #MultipartFile Setting
  servlet:
    multipart:
      enabled: true
      max-file-size: 10485760
      max-request-size: 104857600
      file-size-threshold: 5242880

  #Static Resource
  web:
    resources:
      static-locations:
        - classpath:assets/
        - file:/Users/jangwoo/Desktop/[62]2024.11.포스코DX09/mysite/mysite-upload/

  #thymeleaf
  thymeleaf:
    cache: false
    enable-spring-el-compiler: true
    servlet:
      content-type: text/html
    check-template-location: true
    prefix: classpath:/templates/views/
    suffix: .html
    

  # DB
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.0.120:3306/webdb
    username: webdb
    password: webdb
    hikari:
      minimum-idle: 10
      maximum-pool-size: 20

#Mybatis
mybatis:
  config-location: classpath:mybatis/configuration.xml

server:
  servlet:
    context-path: /mysite07
    encoding:
      charset: UTF-8

  #WhiteLabel Error
  error:
    whitelabel:
      enabled: true
    path: /error

#logging
logging:
  level:
    web: debug
